// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

const String googleMapsApiKey = 'AIzaSyD65Z8_du1vWaNo2p0qzfjH-kkZHMbNFjU';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwWw8TVV1SmFhDOOErk4vC55edy7gAwcg',
    appId: '1:910341618942:web:ea928823ebc2ee599af9af',
    messagingSenderId: '910341618942',
    projectId: 'dookifinder',
    authDomain: 'dookifinder.firebaseapp.com',
    storageBucket: 'dookifinder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwE49nUTVLMEhcKHvJYRGL-GZOZuT5_pg',
    appId: '1:910341618942:android:4d377078a28737c29af9af',
    messagingSenderId: '910341618942',
    projectId: 'dookifinder',
    storageBucket: 'dookifinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz489Yo3-Jd-QSne89slFjTmUGv8ntJAA',
    appId: '1:910341618942:ios:8641fe0e407a3d8c9af9af',
    messagingSenderId: '910341618942',
    projectId: 'dookifinder',
    storageBucket: 'dookifinder.firebasestorage.app',
    iosBundleId: 'com.example.dookifinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz489Yo3-Jd-QSne89slFjTmUGv8ntJAA',
    appId: '1:910341618942:ios:8641fe0e407a3d8c9af9af',
    messagingSenderId: '910341618942',
    projectId: 'dookifinder',
    storageBucket: 'dookifinder.firebasestorage.app',
    iosBundleId: 'com.example.dookifinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwWw8TVV1SmFhDOOErk4vC55edy7gAwcg',
    appId: '1:910341618942:web:84aec41fea757e8d9af9af',
    messagingSenderId: '910341618942',
    projectId: 'dookifinder',
    authDomain: 'dookifinder.firebaseapp.com',
    storageBucket: 'dookifinder.firebasestorage.app',
  );
}
